# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.slugger:
            class:  AppBundle\Utils\Slugger
    
    app.twig.slugify:
        class:     AppBundle\Twig\SlugifyExtension
        arguments: ["@app.slugger"]
        tags:
                - { name: twig.extension }
            
    custom.success_handler:
            class:  AppBundle\Handler\SuccessHandler
            arguments: [@router]
    custom.error_handler:
            class:  AppBundle\Handler\ErrorHandler
            
    #custom fields
    
    #array_to_time_select:
#        class: AppBundle\Form\CustomFields\ArrayToTimeSelectType
#        tags:
#            - { name: form.type, alias: array_to_time_select }